Inny_na_5.0/Kolokwium1Service/Models/ErrorViewModel.cs
namespace Kolokwium1Service.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Inny_na_5.0/Kolokwium1Service/Models/UczestnicyAddModel.cs
using Kolokwium1Storage.Dtos;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.Framework;

namespace Kolokwium1Service.Models
{
    public class UczestnicyAddModel : UczestnicyDto
    {
        public List<SelectListItem>? Konkursy { get; set; }
    }
}

Inny_na_5.0/Kolokwium1Service/Controllers/HomeController.cs
using Kolokwium1Service.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Kolokwium1Service.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Inny_na_5.0/Kolokwium1Service/Controllers/UczestnicyController.cs
using Kolokwium1Service.Models;
using Kolokwium1Storage.Dtos;
using Kolokwium1Storage.Entities;
using Kolokwium1Storage.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Kolokwium1Service.Controllers
{
    public class UczestnicyController : Controller
    {
        private readonly IUczestnicyService _uczestnicyService;
        public UczestnicyController(IUczestnicyService uczestnicyService)
        {
            _uczestnicyService = uczestnicyService;
        }
        // GET: UczestnicyContoller
        public ActionResult Index()
        {
            var result = _uczestnicyService.Read();
            return View(result);
        }
        // GET: UczestnicyContoller/Create
        public ActionResult Create()
        {
            var model = new UczestnicyAddModel();
            model.Konkursy = _uczestnicyService.ReadKonkursy().Select(konkurs => new SelectListItem
            {
                Text = konkurs.Nazwa,
                Value = konkurs.Id.ToString(),
            }).ToList();
            return View(model);
        }
        // POST: UczestnicyContoller/Create
        [HttpPost]
        public ActionResult Create(UczestnicyAddModel model)
        {
            if (ModelState.IsValid)
            {
                _uczestnicyService.Create(model);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: UczestnicyContoller/Update/5
        public ActionResult Update(int id)
        {
            var uczestnik = _uczestnicyService.Read().FirstOrDefault(x => x.Id == id);
            Console.WriteLine("Uczestnik", id, uczestnik.Id);
            var model = new UczestnicyAddModel()
            {
                Id = uczestnik.Id,
                Imie = uczestnik.Imie,
                Nazwisko = uczestnik.Nazwisko,
                Email = uczestnik.Email,
                KonkursId = uczestnik.KonkursId
            };
            model.Konkursy = _uczestnicyService.ReadKonkursy().Select(konkurs => new SelectListItem
            {
                Text = konkurs.Nazwa,
                Value = konkurs.Id.ToString(),
            }).ToList();
            return View(model);
        }

        // POST: UczestnicyContoller/Update/5
        [HttpPost]
        public ActionResult Update(int id, UczestnicyAddModel model)
        {
            if (ModelState.IsValid)
            {
                _uczestnicyService.Update(model);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // POST: UczestnicyContoller/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            Console.WriteLine("Siema:" + id);
            _uczestnicyService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Inny_na_5.0/Kolokwium1Service/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kolokwium1Service</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Kolokwium1Service.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Uczestnicy" asp-action="Index">Kolokwium1Service</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
@*                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Kolokwium1Service - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Inny_na_5.0/Kolokwium1Service/Views/Uczestnicy/Create.cshtml
@model UczestnicyAddModel;
@{
    ViewData["Title"] = "Dodaj uczestnika";
}
<h2>Dodaj rezerwację</h2>
<form method="post" asp-action="Create">
    <div class="form-group">
        <label for="Imie" asp-for="Imie">Imię</label>
        <input type="text" class="form-control" id="Imie" name="Imie" placeholder="Imię" asp-for="Imie">
        <span class="text-danger" asp-validation-for="Imie"></span>
    </div>
    <div class="form-group">
        <label for="Nazwisko" asp-for="Nazwisko">Nazwisko</label>
        <input type="text" class="form-control" id="Nazwisko" name="Nazwisko" placeholder="Nazwisko" asp-for="Nazwisko">
        <span class="text-danger" asp-validation-for="Nazwisko"></span>
    </div>
    <div class="form-group">
        <label for="Email" asp-for="Email">Email</label>
        <input type="email" class="form-control" id="Email" name="Email" placeholder="Email" asp-for="Email">
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class="form-group">
        <label for="KonkursId">Konkurs</label>
        <select required class="form-control" id="KonkursId" name="KonkursId" asp-for="KonkursId" asp-items="Model.Konkursy">
            <option value="">Wybierz konkurs</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Dodaj</button>
</form>

Inny_na_5.0/Kolokwium1Service/Views/Uczestnicy/Index.cshtml
@using Kolokwium1Storage.Dtos;
@model IEnumerable<UczestnicyDto>
@{
    ViewData["Title"] = "Uczestnicy";
}
@if (Model.Any())
{
    <table class="table">
        <thead class="tab-pane">
            <tr>
                <th>Imię</th>
                <th>Nazwisko</th>
                <th>Email</th>
                <th>Konkurs</th>
                <th>
                    <p>
                        <a class="btn btn-outline-primary" asp-action="Create">Dodaj uczestnika</a>
                    </p>
                </th>
            </tr>
        </thead>
        <tbody class="tab-content">
            @foreach (var uczestnik in Model)
            {
                <tr>
                    <td>@uczestnik.Imie</td>
                    <td>@uczestnik.Nazwisko</td>
                    <td>@uczestnik.Email</td>
                    <td>@uczestnik.KonkursNazwa</td>
                    <td>
                        <form method="get" asp-action="Update" asp-route-id="@uczestnik.Id">
                            <button type="submit" class="btn btn-outline-warning">Edytuj</button>
                        </form>
                        <form method="post" asp-action="Delete" asp-route-id="@uczestnik.Id">
                            <button type="submit" class="btn btn-outline-danger">Usuń</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Brak uczestników</p>
    <p>
        <a class="btn btn-outline-primary" asp-action="Create">Dodaj uczestnika</a>
    </p>
}

Inny_na_5.0/Kolokwium1Service/Views/Uczestnicy/Update.cshtml
@model UczestnicyAddModel;
@{
    ViewData["Title"] = "Edytuj uczestnika";
}
<h2>Edytuj rezerwację</h2>
<form method="post" asp-action="Update">
    <div class="form-group">
        <label for="Imie" asp-for="Imie">Imię</label>
        <input type="text" class="form-control" id="Imie" name="Imie" placeholder="Imię" asp-for="Imie">
        <span class="text-danger" asp-validation-for="Imie"></span>
    </div>
    <div class="form-group">
        <label for="Nazwisko" asp-for="Nazwisko">Nazwisko</label>
        <input type="text" class="form-control" id="Nazwisko" name="Nazwisko" placeholder="Nazwisko" asp-for="Nazwisko">
        <span class="text-danger" asp-validation-for="Nazwisko"></span>
    </div>
    <div class="form-group">
        <label for="Email" asp-for="Email">Email</label>
        <input type="email" class="form-control" id="Email" name="Email" placeholder="Email" asp-for="Email">
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>
    <div class="form-group">
        <label for="KonkursId">Konkurs</label>
        <select required class="form-control" id="KonkursId" name="KonkursId" asp-for="KonkursId" asp-items="Model.Konkursy">
            <option value="">Wybierz konkurs</option>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Dodaj</button>
</form>